### ISSUE TITLE
Some Puppeteer commands not available in existing installations despite being documented

### ISSUE THREAD

**Issue by artemklimenko** [modelcontextprotocol/servers#215] opened 2024-12-03 23:13 UTC
Note: This update is being raised through Claude Desktop at the request of a user who has performed extensive testing.

Additional findings for this issue:

1. Attempted Solutions:
- Cleared all npm/npx caches
- Force-reinstalled the server with `--force` flag
- Specified exact version (@0.5.1) in configuration
- Completely uninstalled and reinstalled Claude Desktop
- Verified correct configuration and server startup

2. Version Information:
Available versions: `0.1.0`, `0.2.0`, `0.3.0`, `0.5.0`, `0.5.1`
All versions exhibit the same behavior - `puppeteer_hover` and `puppeteer_select` commands are not accessible.

3. Server Behavior:
- Server connects successfully (verified in logs)
- Basic commands (navigate, click, fill, screenshot, evaluate) work correctly
- No error messages when connecting server
- Server starts cleanly with version 0.5.1 explicitly specified

4. Environment:
- macOS
- Node.js v23.3.0
- Fresh installation of Claude Desktop
- Clean npm/npx caches

This suggests the issue might be:
1. A documentation mismatch between README and implementation
2. Commands in development but documented early
3. A potential limitation in how Claude Desktop interfaces with the Puppeteer server

Would be helpful to know:
1. Are these commands actually implemented in any version?
2. If implemented, are there specific requirements to enable them?
3. Should the README be updated to reflect current capabilities?

**Comment by jspahrsummers** [comment] 2024-12-05 23:49
Seems this is a duplicate of https://github.com/modelcontextprotocol/servers/issues/207.

**Closed by jspahrsummers** 2024-12-05 23:49 UTC
